apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false # don't push on Docker on build
  artifacts:
    - image: nkolchakov/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual: # manual configuration on what to do on file change
          - src: 'src/**/*.ts'
            dest: '.'
    - image: nkolchakov/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: '.'
    - image: nkolchakov/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: '.'
    - image: nkolchakov/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: '.'
    - image: nkolchakov/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: '.'
    - image: nkolchakov/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: '.'
